language: c
compiler: gcc
dist: focal
python:
  - "3.6"

addons:
  apt:
    update: true
    packages:
      - autoconf-archive
      - uuid-dev
      - libjson-c-dev
      - lcov
      - libgtk-3-0
      - libgtk-3-dev
      - libcairo2
      - libcairo2-dev
      - uuid-dev

script:
    - autoreconf -fi
    - mkdir build && cd build && ../configure --enable-code-coverage
    - make check -j $(nproc)

jobs:
    include:
        -   stage: Code Coverage
            after_success:
                - bash <(curl -s https://codecov.io/bash)
