name: uFSM Build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
          sudo apt-get update
          sudo apt-get install autoconf-archive libjson-c-dev lcov libgtk-3-0 libgtk-3-dev libcairo2 libcairo2-dev uuid-dev
    - name: configure
      run: mkdir build && autoreconf -fi && cd build && ../configure --enable-code-coverage CFLAGS="-O0"
    - name: build
      run: cd build && make -j $(nproc)
    - name: test
      run: cd build && make check
    - name: codecov
      run: cd build/libufsm-core && bash <(curl -s https://codecov.io/bash)
